
FUNC MAIN: 0
    LOAD_ACCI "ImAlright!\n"
    CALL_INTRINSIC PRINTS
    
    LOAD_ACCI 100
    CALL_INTRINSIC SCANS
    STORE_ACC x0

    LOAD_ACCI 100
    CALL_INTRINSIC SCANS
    STORE_ACC x1

    LOAD_ACC x0
    CALL_INTRINSIC PRINTS

    LOAD_ACCI "\n"
    CALL_INTRINSIC PRINTS

    LOAD_ACC x1
    CALL_INTRINSIC PRINTS

    LOAD_ACCI "\n"
    CALL_INTRINSIC PRINTS

    LOAD_ACCI "ThatsFine\n"
    CALL_INTRINSIC PRINTS

    RET